# How to use conditionals in Ansible Playbooks
- hosts: all
  vars:
    - create_user_file: yes
    - user: biruk
  tasks:
    - name: create file for user
      file:
        path: /home/{{user}}/myfile
        state: touch
      when: create_user_file
