# When installing mutliple packages, you can use a loop and provide an array containing
# the names of the packages you want to install.
# 
# Example installing vim, unzip, and curl
#

- hosts: all
  become: yes
  tasks:
    - name: Update apt cache and make sure Vim, Curl, and Unzip are installed
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - vim
        - curl
        - unzip
