# Recovering from Errors
# --------------------------

# Ansible Blocks
# ----------------
# - `blocks` are clauses that logically group tasks as a unit
# - They can be used to control how tasks are executed
# - For example, a `block` can have a `when` conditional applied to the entire block
# - This means that all the tasks in the block will only run if the conditional is met

# Block and Rescue
# -----------------
# A block can have a set of tasks grouped in a rescue statement
# The tasks in the rescue statement only run if a task in the block fails

---
- name: Utilize block, rescue, and always
  hosts: db
  become: true

  tasks:
    - name: Update database
      block:
        - name: Display an update message
          debug:
            msg: "Updating database"
        - name: Update postgreSQL server to latest version
          yum:
            name: postgresql-server
            state: latest
      rescue:
        - name: Display error message that database will be restarted
          debug:
            msg: "Update failed. Restarting database to correct issues."
        - name: Restart the database if upgrade failed
          service:
            name: postgresql
            state: restarted
      always:
        - name: Notify user of reboot after update attempt
        debug:
          msg: "Uupdate process has completed."
        - name: Reboot the system
          reboot:
