# Ansible examples
#
# Install Nginx using Ansible
#

# - From the list of hosts we are going to the `web` hosts made `become` global for a sudo password
# - On task step 1) installed nginx using apt ( sudo apt install nginx latest)
# - task step 2) started nginx as a service

- hosts: web
  become: yes
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
        name: nginx
        state: started
